name: ML Training CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib dagshub

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          python modelling.py 100 10

      - name: Get latest MLflow run_id
        run: cat MLProject/latest_run_id.txt

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            MLProject/confusion_matrix.png
            MLProject/latest_run_id.txt